[settings]
idiomatic_version_file_enable_tools = ["terraform", "python"]

[tools]
bun = "latest"
krew = "latest"
kubectl = "latest"
terraform = "latest"
uv = "latest"
helm = "latest"
kustomize = "latest"
talosctl = "latest"
oc = "latest"
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }
aws-cli = { version = "latest", symlink_bins = "true" }
pitchfork = "latest"
hk = "latest"
usage = "latest"
