[settings]
idiomatic_version_file_enable_tools = ["terraform", "python"]

[tools]
bun = "latest"
krew = "latest"
kubectl = "latest"
terraform = "latest"
uv = "latest"
helm = "latest"
kustomize = "latest"
talosctl = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
oc = "latest"
k9s = "latest"
k3d = "latest"
